Models/FitnessCategory.cs
using System.ComponentModel.DataAnnotations;

namespace GymManagement.Models
{
    public class FitnessCategory : Auditable
    {
        public int ID { get; set; }

        [Display(Name = "Category")]
        public string Summary => (ExerciseCategories.Count()==0) ? Category
            : Category + " (" + ExerciseCategories.Count() + " Exercises)";

        [Required(ErrorMessage = "You cannot leave the category name blank.")]
        [StringLength(50, ErrorMessage = "Category name cannot be more than 50 characters long.")]
        public string Category { get; set; } = "";

        [Display(Name = "Group Classes")]
        public ICollection<GroupClass> GroupClasses { get; set; } = new HashSet<GroupClass>();

        [Display(Name = "Exercises")]
        public ICollection<ExerciseCategory> ExerciseCategories { get; set; } = new HashSet<ExerciseCategory>();

    }
}

Controllers/FitnessCategoryController.cs
using GymManagement.CustomControllers;
using GymManagement.Data;
using GymManagement.Models;
using GymManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;

namespace GymManagement.Controllers
{
    [Authorize]
    public class FitnessCategoryController : CognizantController
    {
        private readonly GymContext _context;

        public FitnessCategoryController(GymContext context)
        {
            _context = context;
        }

        // GET: FitnessCategory
        public async Task<IActionResult> Index()
        {
            var fitnessCategories = await _context.FitnessCategories
                .Include(c=>c.ExerciseCategories)
                .AsNoTracking()
                .ToListAsync();
            return View(fitnessCategories);
        }

        // GET: FitnessCategory/Details/5
        [Authorize(Roles = "Staff, Supervisor, Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fitnessCategory = await _context.FitnessCategories
                .Include(fc => fc.ExerciseCategories).ThenInclude(e => e.Exercise)
                .AsNoTracking()
                .FirstOrDefaultAsync(fc => fc.ID == id);

            if (fitnessCategory == null)
            {
                return NotFound();
            }

            return View(fitnessCategory);
        }

        // GET: FitnessCategory/Create
        [Authorize(Roles = "Staff, Supervisor, Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: FitnessCategory/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Staff, Supervisor, Admin")]
        public async Task<IActionResult> Create([Bind("Category")] FitnessCategory fitnessCategory)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(fitnessCategory);
                    await _context.SaveChangesAsync();
                    var returnUrl = ViewData["returnURL"]?.ToString();
                    if (string.IsNullOrEmpty(returnUrl))
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    return Redirect(returnUrl);
                }
            }
            catch (DbUpdateException dex)
            {
                ExceptionMessageVM msg = new();
                string baseMessage = dex.GetBaseException().Message;

                if (baseMessage.Contains("UNIQUE") && baseMessage.Contains("Category"))
                {
                    msg.ErrProperty = "Category";
                    msg.ErrMessage = "Unable to save changes. Remember, " +
                        "you cannot have duplicate Fitness Category Name.";
                }
                else
                {
                    msg.ErrProperty = string.Empty;
                }

                ModelState.AddModelError(msg.ErrProperty, msg.ErrMessage);
            }
            //Decide if we need to send the Validaiton Errors directly to the client
            if (!ModelState.IsValid && Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                //Was an AJAX request so build a message with all validation errors
                string errorMessage = "";
                foreach (var modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errorMessage += error.ErrorMessage + "|";
                    }
                }
                //Note: returning a BadRequest results in HTTP Status code 400
                return BadRequest(errorMessage);
            }

            return View(fitnessCategory);
        }

        // GET: FitnessCategory/Edit/5
        [Authorize(Roles = "Staff, Supervisor, Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fitnessCategory = await _context.FitnessCategories.FindAsync(id);
            if (fitnessCategory == null)
            {
                return NotFound();
            }
            return View(fitnessCategory);
        }

        // POST: FitnessCategory/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Staff, Supervisor, Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            //Go get the Doctor to update
            var fitnessCategoryToUpdate = await _context.FitnessCategories
                .FirstOrDefaultAsync(p => p.ID == id);

            //Check that you got it or exit with a not found error
            if (fitnessCategoryToUpdate == null)
            {
                return NotFound();
            }

            //Try updating it with the values posted
            if (await TryUpdateModelAsync<FitnessCategory>(fitnessCategoryToUpdate, "",
                d => d.Category))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    var returnUrl = ViewData["returnURL"]?.ToString();
                    if (string.IsNullOrEmpty(returnUrl))
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    return Redirect(returnUrl);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FitnessCategoryExists(fitnessCategoryToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException dex)
                {
                    ExceptionMessageVM msg = new();
                    string baseMessage = dex.GetBaseException().Message;

                    if (baseMessage.Contains("UNIQUE") && baseMessage.Contains("Category"))
                    {
                        msg.ErrProperty = "Category";
                        msg.ErrMessage = "Unable to save changes. Remember, " +
                            "you cannot have duplicate Fitness Category Name.";
                    }
                    else
                    {
                        msg.ErrProperty = string.Empty;
                    }

                    ModelState.AddModelError(msg.ErrProperty, msg.ErrMessage);
                }
                //Decide if we need to send the Validaiton Errors directly to the client
                if (!ModelState.IsValid && Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    //Was an AJAX request so build a message with all validation errors
                    string errorMessage = "";
                    foreach (var modelState in ViewData.ModelState.Values)
                    {
                        foreach (ModelError error in modelState.Errors)
                        {
                            errorMessage += error.ErrorMessage + "|";
                        }
                    }
                    //Note: returning a BadRequest results in HTTP Status code 400
                    return BadRequest(errorMessage);
                }
            }
            return View(fitnessCategoryToUpdate);
        }

        // GET: FitnessCategory/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fitnessCategory = await _context.FitnessCategories
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (fitnessCategory == null)
            {
                return NotFound();
            }

            return View(fitnessCategory);
        }

        // POST: FitnessCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fitnessCategory = await _context.FitnessCategories.FindAsync(id);
            try
            {
                if (fitnessCategory != null)
                {
                    _context.FitnessCategories.Remove(fitnessCategory);
                }

                await _context.SaveChangesAsync();
                var returnUrl = ViewData["returnURL"]?.ToString();
                if (string.IsNullOrEmpty(returnUrl))
                {
                    return RedirectToAction(nameof(Index));
                }
                return Redirect(returnUrl);
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("FOREIGN KEY constraint failed"))
                {
                    ModelState.AddModelError("", "Unable to Delete Fitness Category. " +

Views/FitnessCategory/Create.cshtml
@model GymManagement.Models.FitnessCategory

<partial name="_ViewHeading" />

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <partial name="_BackToList" />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FitnessCategory/Delete.cshtml
@model GymManagement.Models.FitnessCategory

<partial name="_ViewHeading" />

<div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <partial name="_BackToList" />
    </form>
</div>

Views/FitnessCategory/Details.cshtml
@model GymManagement.Models.FitnessCategory

<partial name="_ViewHeading" />

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => Model.ExerciseCategories)
        </dt>
        <dd class="col-sm-10">
            @{
                int exerciseCount = Model.ExerciseCategories.Count;
                if (exerciseCount > 0)
                {
                    string firstExercise = Model.ExerciseCategories.FirstOrDefault().Exercise.Name;
                    if (exerciseCount > 1)
                    {
                        string exerciseList = "";
                        var c = Model.ExerciseCategories.ToList();
                        for (int i = 1; i < exerciseCount; i++)
                        {
                            exerciseList += c[i].Exercise.Name + " <br />";
                        }
                        <a class="" role="button" data-bs-toggle="collapse" href="#collapseHistory@(Model.ID)"
                           aria-expanded="false" aria-controls="collapseHistory@(Model.ID)">
                            @firstExercise <span class="badge bg-info">@exerciseCount</span>
                        </a>
                        <div class="collapse" id="collapseHistory@(Model.ID)">
                            @Html.Raw(exerciseList)
                        </div>
                    }
                    else
                    {
                        @firstExercise
                    }
                }
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <partial name="_BackToList" />
</div>

Views/FitnessCategory/Edit.cshtml
@model GymManagement.Models.FitnessCategory

<partial name="_ViewHeading" />

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <partial name="_BackToList" />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FitnessCategory/Index.cshtml
@model IEnumerable<GymManagement.Models.FitnessCategory>

<partial name="_ViewHeading" />
@if (User.IsInRole("Admin") || User.IsInRole("Supervisor") || User.IsInRole("Staff"))
{
    <p>
        <a asp-action="Create">Create New @ViewData["ControllerFriendlyName"]</a>
    </p>

    <div class="card mb-sm-3" style="min-width: 18rem;">
        <h4 class="card-header" id="AppointmentReason">Upload Fitness Categories</h4>
        <div class="card-body">
            <div class="text-danger">@Html.Raw(TempData["Feedback"])</div>
                <form asp-action="InsertFromExcel" asp-controller="FitnessCategory" method="post" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label custom-file-label">Upload Excel File:</label>
                                <div class="input-group mb-3">
                                    <input type="file" class="form-control" name="theExcel" id="theExcel">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Upload Data" class="btn btn-dark" />
                            </div>
                        </div>
                        <div class="col-md-7 mt-3">
                            <p>
                                Put all the data to upload into the Excel spreadsheet with the first column for <strong>Exercise</strong> and the second column for <strong>FitnessCategory</strong>.
                                Download testing file: <a href="/files/SampleData.xlsx" download><i class="fas fa-file-excel excel-icon"></i>SampleData.xlsx</a>
                            </p>
                        </div>
                    </div>
                </form>
        </div>
    </div>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Summary)
            </td>
            @if (User.IsInRole("Admin") || User.IsInRole("Supervisor") || User.IsInRole("Staff"))
            {
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                    @if (User.IsInRole("Admin"))
                    {
                      <span> | </span> <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    }
                </td>
            }
        </tr>
}
    </tbody>
</table>