Controllers/ClientWorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GymManagement.Data;
using GymManagement.Models;
using GymManagement.Utilities;
using System.Drawing.Printing;
using GymManagement.ViewModels;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using GymManagement.CustomControllers;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using Microsoft.EntityFrameworkCore.Storage;
using NuGet.Packaging;
using Microsoft.AspNetCore.Authorization;

namespace GymManagement.Controllers
{
    [Authorize(Roles = "Client, Staff, Supervisor, Admin")]
    public class ClientWorkoutController : ElephantController
    {
        private readonly GymContext _context;
        private static readonly string[] DurationItems = ["10", "20", "30", "40", "50", "60", "70", "80", "90", "120"];

        public ClientWorkoutController(GymContext context)
        {
            _context = context;
        }

        // GET: Workout
        public async Task<IActionResult> Index(int? ClientID, int? page, int? pageSizeID, int? InstructorID, 
            string actionButton, string SearchString, string sortDirection = "desc", string sortField = "Workout")
        {
            //Get the URL with the last filter, sort and page parameters from THE CLIENTS Index View
            ViewData["returnURL"] = MaintainURL.ReturnURL(HttpContext, "Client");

            if (User.IsInRole("Client"))
            {
                string clientUser = User?.Identity?.Name;
                ClientID = _context.Clients.Where(c => c.Email == clientUser)
                            .Select(c => c.ID).FirstOrDefault();
            }

            if (!ClientID.HasValue)
            {
                //Go back to the proper return URL for the Clients controller
                return Redirect(ViewData["returnURL"].ToString());
            }

            PopulateDropDownLists();

            //Count the number of filters applied - start by assuming no filters
            ViewData["Filtering"] = "btn-outline-secondary";
            int numberFilters = 0;
            //Then in each "test" for filtering, add to the count of Filters applied

            //NOTE: make sure this array has matching values to the column headings
            string[] sortOptions = new[] { "Workout", "Instructor" };

            var workouts = _context.Workouts
                .Include(w => w.Client)
                .Include(w => w.Instructor)
                .Include(w => w.WorkoutExercises).ThenInclude(e => e.Exercise)
                .Where(w => w.ClientID == ClientID.GetValueOrDefault())
                .AsNoTracking();

            if (InstructorID.HasValue)
            {
                workouts = workouts.Where(p => p.InstructorID == InstructorID);
                numberFilters++;
            }
            if (!String.IsNullOrEmpty(SearchString))
            {
                workouts = workouts.Where(p => p.Notes.ToUpper().Contains(SearchString.ToUpper()));
                numberFilters++;
            }

            //Give feedback about the state of the filters
            if (numberFilters != 0)
            {
                //Toggle the Open/Closed state of the collapse depending on if we are filtering
                ViewData["Filtering"] = " btn-danger";
                //Show how many filters have been applied
                ViewData["numberFilters"] = "(" + numberFilters.ToString()
                    + " Filter" + (numberFilters > 1 ? "s" : "") + " Applied)";
                //Keep the Bootstrap collapse open
                //@ViewData["ShowFilter"] = " show";
            }
            //Before we sort, see if we have called for a change of filtering or sorting
            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted so lets sort!
            {
                page = 1;//Reset back to first page when sorting or filtering

                if (sortOptions.Contains(actionButton))//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
            }
            //Now we know which field and direction to sort by.
            if (sortField == "Instructor")
            {
                if (sortDirection == "asc")
                {
                    workouts = workouts
                        .OrderBy(w => w.Instructor.LastName)
                        .ThenBy(w => w.Instructor.FirstName);
                }
                else
                {
                    workouts = workouts
                        .OrderByDescending(w => w.Instructor.LastName)
                        .ThenByDescending(w => w.Instructor.FirstName);
                }
            }
            else //Workout Date
            {
                if (sortDirection == "asc")
                {
                    workouts = workouts
                        .OrderBy(p => p.StartTime);
                }
                else
                {
                    workouts = workouts
                        .OrderByDescending(p => p.StartTime);
                }
            }
            //Set sort for next time
            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;

            //Now get the MASTER record, the cleint, so it can be displayed at the top of the screen
            Client? client = await _context.Clients
                    .Include(c => c.MembershipType)
                    .Include(c => c.ClientThumbnail)
                    .Include(c => c.Enrollments).ThenInclude(e => e.GroupClass).ThenInclude(g => g.FitnessCategory)
                    .Include(c => c.Enrollments).ThenInclude(e => e.GroupClass).ThenInclude(g => g.ClassTime)
                    .AsNoTracking()
                    .FirstOrDefaultAsync(c => c.ID == ClientID.GetValueOrDefault());

            ViewBag.Client = client;



            //Handle Paging
            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID, ControllerName());
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);

            var pagedData = await PaginatedList<Workout>.CreateAsync(workouts.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);

        }

        // GET: Workout/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workout = await _context.Workouts
                .Include(w => w.Client)
                .Include(w => w.Instructor)
                .Include(w => w.WorkoutExercises).ThenInclude(e => e.Exercise)
                .ThenInclude(e => e.ExerciseCategories).ThenInclude(f => f.FitnessCategory)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id); 

            if (workout == null)
            {
                return NotFound();
            }

            return View(workout);
        }

        // GET: Workout/Add
        [Authorize(Roles = "Staff, Supervisor, Admin")]
        public IActionResult Add(int? ClientID, string ClientName)
        {
            if (!ClientID.HasValue)
            {
                return Redirect(ViewData["returnURL"].ToString());
            }

            Workout workout = new Workout()
            {
                ClientID = ClientID.GetValueOrDefault(),
                StartTime = DateUtilities.GetNextWeekday(DateTime.Today, 3)
            };
            PopulateDropDownLists();
            PopulateAssignedExerciseData(workout);
            ViewData["ClientName"] = ClientName;
            ViewData["Duration"] = new SelectList(DurationItems, "20");

            return View(workout);
        }

        // POST: Workout/Add
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Staff, Supervisor, Admin")]
        public async Task<IActionResult> Add([Bind("ID,StartTime,EndTime,Notes,ClientID,InstructorID")] 
            Workout workout, string[] selectedOptions, string ClientName, int? Duration)
        {
            try
            {
                int duration = (Duration == null) ? 30 : Duration.GetValueOrDefault();
                workout.EndTime = workout.StartTime.AddMinutes(duration);

                UpdateWorkoutExercise(selectedOptions, workout);

                if (ModelState.IsValid)
                {
                    WorkoutConflictVM workoutConflict = Overlapping(workout);
                    if (workoutConflict.isConflict)
                    {
                        ModelState.AddModelError("", workoutConflict.Comment);
                    }
                    else
                    {
                        _context.Add(workout);
                        await _context.SaveChangesAsync();
                        return Redirect(ViewData["returnURL"].ToString());
                    }
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
            }
            catch (DbUpdateException)

Views/ClientWorkout/Add.cshtml
@model GymManagement.Models.Workout

@{
    ViewData["Title"] = "Add Workout";
}

<h2>Add Workout for Client: @ViewData["ClientName"]</h2>
<hr />
<form asp-action="Add">
    <input type="hidden" name="ClientID" value="@Model.ClientID" />
    <input type="hidden" name="ClientName" value="@ViewData["ClientName"]" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Duration (30 minute default)</label>
                @Html.DropDownList("Duration", null, "How Many Minutes",
                         htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <textarea asp-for="Notes" rows="5" cols="40" class="form-control"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstructorID" class="control-label"></label>
                <select asp-for="InstructorID" class ="form-control" asp-items="ViewBag.InstructorID">
                    <option value="">No Instructor</option>
                </select>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label"> Exercises Added</label> <button type="button" id="btnRight" class="btn btn-danger btn-sm">
                        <strong>-</strong>
                    </button>
                    @Html.ListBox("selectedOptions", (MultiSelectList)ViewBag.selOpts, new { @size = 10, @class = "form-control" })
                </div>

                <div class="form-group col-md-6">
                    <label class="control-label"> Choose Exercises</label> <button type="button" id="btnLeft" class="btn btn-success btn-sm">
                        <strong>+</strong>
                    </button>
                    @Html.ListBox("availOptions", (MultiSelectList)ViewBag.availOpts, new { @size = 10, @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" id="btnSubmit" value="Add" class="btn btn-primary" />
    </div>
</form>
<div>
    <partial name="_BackToList" />
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/multiselect.js"></script>
}

Views/ClientWorkout/Details.cshtml
@model GymManagement.Models.Workout

@{
    ViewData["Title"] = "Workout Details";
}

<h2>Workout Details for Client:  @Model.Client.Summary</h2>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDateSummary)
            @Html.DisplayFor(model => model.StartTimeSummary)
            <span class="break-word">
                (@Html.DisplayFor(model => model.DurationSummary))
            </span>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTimeSummary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instructor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instructor.Summary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WorkoutExercises)
        </dt>
        <dd class="col-sm-10">
            @{
                var exercises = Model.WorkoutExercises.ToList();
                int exerciseCount = exercises.Count;
                if (exerciseCount > 0)
                {
                    string firstExercise = exercises[0].Exercise.Summary;
                    if (exerciseCount > 1)
                    {
                        string exerciseList = "";
                        for (int i = 1; i < exerciseCount; i++)//Skip the first because we have it already
                        {
                            exerciseList += exercises[i].Exercise.Summary + " <br />";
                        }
                        <a class="" role="button" data-bs-toggle="collapse" href="#collapseHistory@(Model.ID)"
                           aria-expanded="false" aria-controls="collapseHistory@(Model.ID)">
                            @firstExercise <span class="badge bg-info">@exerciseCount</span>
                        </a>
                        <div class="collapse" id="collapseHistory@(Model.ID)">
                            @Html.Raw(exerciseList)
                        </div>
                    }
                    else
                    {
                        @firstExercise
                    }
                }
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Update" asp-route-id="@Model?.ID">Update Workout</a> |
    <partial name="_BackToList" />
</div>

Views/ClientWorkout/Index.cshtml
@model IEnumerable<GymManagement.Models.Workout>

@{
    GymManagement.Models.Client client = (GymManagement.Models.Client)ViewBag.Client;
    <partial name="_ClientDetail" model="client" />
    ViewData["Title"] = ViewData["ControllerFriendlyName"];
}

<form asp-action="Index" method="get">
    <input type="hidden" name="sortDirection" value="@ViewData["sortDirection"]" />
    <input type="hidden" name="sortField" value="@ViewData["sortField"]" />
    <input type="hidden" name="ClientID" value="@client.ID" />
    <div class="form-horizontal">
        <button class="btn @(ViewData["Filtering"])" type="button" data-bs-toggle="collapse" id="filterToggle" data-bs-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter">
            Filter/Search @ViewData["numberFilters"]
        </button><br />
        <div class="collapse @ViewData["ShowFilter"]" id="collapseFilter">
            <div class="collapse card card-body bg-light" style="padding-top: 10px; padding-bottom: 5px;" id="collapseFilter">
                <div class="row">
                    <div class="form-group col-md-4 ml-md-3">
                        <label class="control-label">Instructor:</label>
                        @Html.DropDownList("InstructorID", null, "All Instructors", htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label">Search Notes:</label>
                        @Html.TextBox("SearchString", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4 align-self-end">
                        <input type="submit" name="actionButton" value="Apply" class="btn btn-primary" />
                        <a asp-action="Index" asp-route-ClientID="@client.ID">Clear</a>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <table class="table">
                <col />
                <col />
                <col style="width:30%">
                <col style="width:20%">
                <col />
                <thead>
                    <tr>
                        <th>
                            <input type="submit" name="actionButton" value="Workout" class="btn btn-link" />
                        </th>
                        <th>
                            <input type="submit" name="actionButton" value="Instructor" class="btn btn-link" />
                        </th>
                        <th class="d-none d-xl-table-cell">
                            <input type="submit" value="Notes" class="btn btn-toolbar" />
                        </th>
                        <th class="d-none d-lg-table-cell">
                            <input type="submit" value="Exercises" class="btn btn-toolbar" />
                        </th>
                        @if (User.IsInRole("Admin") || User.IsInRole("Supervisor") || User.IsInRole("Staff"))
                        {
                            <th class="text-center" style="min-width:140px">
                                <a asp-controller="ClientWorkout" asp-action="Add"
                                   asp-route-ClientID="@client.ID" asp-route-ClientName="@client.Summary">
                                    <span class="btn btn-success" data-bs-toggle="tooltip"
                                          title="Add Appointment"><strong>&#x271A; Add</strong></span>
                                </a>
                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartDateSummary)
                                @Html.DisplayFor(modelItem => item.StartTimeSummary)
                                <span class="break-word">
                                    (@Html.DisplayFor(modelItem => item.DurationSummary))
                                </span>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Instructor.Summary)
                            </td>
                            <td class="d-none d-xl-table-cell">
                                @{
                                    if (item.Notes != null)
                                    {
                                        string[] noteWords = item.Notes.Split(' ');
                                        if (noteWords.Count() > 5)
                                        {
                                            <a class="" role="button" data-bs-toggle="collapse" href="#collapseSum@(item.ID)" aria-expanded="false" aria-controls="collapseSum@(item.ID)">
                                                @(string.Join(" ", noteWords.Take(5)) + "...")
                                            </a>
                                            <div class="collapse" id="collapseSum@(item.ID)">
                                                <div class="well">
                                                    @(string.Join(" ", noteWords.Skip(5)))
                                                </div>
                                            </div>
                                        }
                                        else
                                        {
                                            @item.Notes
                                        }
                                    }
                                }
                            </td>
                            <td class="d-none d-lg-table-cell">
                                @{
                                    int exerciseCount = item.WorkoutExercises.Count;
                                    if (exerciseCount > 0)
                                    {
                                        string firstExercise = item.WorkoutExercises.FirstOrDefault().Exercise.Name;
                                        if (exerciseCount > 1)
                                        {
                                            string exerciseList = "";
                                            var c = item.WorkoutExercises.ToList();
                                            for (int i = 1; i < exerciseCount; i++)//Skip the first because we have it already
                                            {
                                                exerciseList += c[i].Exercise.Name + " <br />";
                                            }
                                            <a class="" role="button" data-bs-toggle="collapse" href="#collapseHistory@(item.ID)"
                                               aria-expanded="false" aria-controls="collapseHistory@(item.ID)">
                                                @firstExercise <span class="badge bg-info">@exerciseCount</span>
                                            </a>
                                            <div class="collapse" id="collapseHistory@(item.ID)">
                                                @Html.Raw(exerciseList)
                                            </div>
                                        }
                                        else
                                        {
                                            @firstExercise
                                        }
                                    }
                                }
                            </td>
                            @if (User.IsInRole("Admin") || User.IsInRole("Supervisor") || User.IsInRole("Staff"))
                            {
                                <td class="text-center" style="min-width:140px">
                                    <a asp-controller="ClientWorkout" asp-action="Update" asp-route-id="@item.ID"
                                       class="btn btn-sm btn-outline-primary" role="button"
                                       data-bs-toggle="tooltip" title="Edit @ViewData["ControllerFriendlyName"]">
                                        &#x270D;
                                    </a>
                                    <a asp-controller="ClientWorkout" asp-action="Details" asp-route-id="@item.ID"
                                       class="btn btn-sm btn-outline-info" role="button"
                                       data-bs-toggle="tooltip" title="@ViewData["ControllerFriendlyName"] Details">
                                        &#x1F50D;
                                    </a>
                                    <a asp-controller="ClientWorkout" asp-action="Remove" asp-route-id="@item.ID"
                                       class="btn btn-sm btn-outline-danger" role="button"
                                       data-bs-toggle="tooltip" title="Delete @ViewData["ControllerFriendlyName"]">
                                        &#x274C;
                                    </a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <partial name="_PagingNavBar" />
    <div>
        <a asp-action="Edit" asp-controller="Client" asp-route-id="@client.ID">Edit @client.Summary</a> |
        <a href='@ViewData["returnURL"]'>Back to Client List</a>
    </div>
</form>
@section Scripts {
    <script type="text/javascript">
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
}

Views/ClientWorkout/Remove.cshtml
@model GymManagement.Models.Workout

@{
    ViewData["Title"] = "Remove Workout";
}

<h2>Remove Workout for Client: @Model.Client.Summary</h2>

<div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDateSummary)
            @Html.DisplayFor(model => model.StartTimeSummary)
            <span class="break-word">
                (@Html.DisplayFor(model => model.DurationSummary))
            </span>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndTimeSummary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Instructor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Instructor.Summary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WorkoutExercises)
        </dt>
        <dd class="col-sm-10">
            @{
                var exercises = Model.WorkoutExercises.ToList();
                int exerciseCount = exercises.Count;
                if (exerciseCount > 0)
                {
                    string firstExercise = exercises[0].Exercise.Summary;
                    if (exerciseCount > 1)
                    {
                        string exerciseList = "";
                        for (int i = 1; i < exerciseCount; i++)//Skip the first because we have it already
                        {
                            exerciseList += exercises[i].Exercise.Summary + " <br />";
                        }
                        <a class="" role="button" data-bs-toggle="collapse" href="#collapseHistory@(Model.ID)"
                           aria-expanded="false" aria-controls="collapseHistory@(Model.ID)">
                            @firstExercise <span class="badge bg-info">@exerciseCount</span>
                        </a>
                        <div class="collapse" id="collapseHistory@(Model.ID)">
                            @Html.Raw(exerciseList)
                        </div>
                    }
                    else
                    {
                        @firstExercise
                    }
                }
            }
        </dd>

    </dl>
    
    <form asp-action="Remove">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <partial name="_BackToList" />
    </form>
</div>